# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    hostname: db
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  blanket:
    build: .
    volumes:
      - ./site:/var/www/html
      # - /var/www/html/content
    ports:
      - 8081:80
