# Use root/example as user/password credentials
version: '3.1'

services:
  blanket:
    build: .
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html

  db:
    image: mariadb
    hostname: db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
